---
- name: Google Cloud Platform
  hosts: localhost
  connection: local
  tasks:
    - name: Creating Instance
      tags: dns
      gce:
        credentials_file: "~/Documents/gcp.json"
        disk_auto_delete: yes
        disk_size: 10
        external_ip: ephemeral
        image: centos-7
        machine_type: n1-standard-1
        name: "meetup-{{ meetup_env }}"
        network: default
        num_instances: 1
        project_id: united-strategy-231002
        service_account_email: shippable@united-strategy-231002.iam.gserviceaccount.com
        state: present
        tags:
          - http-server
          - "{{ meetup_env }}"
        zone: us-central1-a
        metadata: '{"enable-oslogin":"TRUE"}'
      register: gce_instance_info

    - name: Configuring DNS
      tags: dns
      cloudflare_dns:
        zone: lowbit.com.br
        record: meetup-test
        type: A
        value: "{{ gce_instance_info.instance_data.0.public_ip }}"
        account_email: "{{ cloudflare_email }}"
        account_api_token: "{{ cloudflare_api }}"

    - name: Saving Instance to Inventory
      add_host:
        name: "meetup-{{ meetup_env }}"
        ansible_host: "{{ gce_instance_info.instance_data.0.public_ip }}"
        ansible_user: lowbit_lowbit_com_br
        group: meetup

    - name: Waiting for instance to become active (SSH)
      wait_for:
        delay: 1
        host: "{{ gce_instance_info.instance_data.0.public_ip }}"
        port: 22
        state: started
        timeout: 30

- name: Configure Hosts
  hosts: "meetup-{{ meetup_env }}"
  become: yes
  roles:
    - role: system-timezone
    - role: docker-install
      docker_version: 18.06
      docker_storage_driver: overlay
      docker_registry_use: false
      docker_log_max_file: 5
      docker_log_max_size: 50m
      docker_user_home: /home/docker
      docker_user_pass: D0ck3r_Us3r_P4ssw0rd
      proxy_use: false
  post_tasks:
    - name: Deploy Meetup Application
      docker_container:
        name: meetup-app
        image: "lowbit/meetup-app:{{ meetup_version }}"
        state: started
        ports:
         - "80:3000"
