- name: Inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Adding Google Cloud instance to the inventory
      add_host:
        name: "qconsp-{{ service_name }}-{{ service_env }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: lowbit_lowbit_com_br
        ansible_ssh_private_key_file: "{{ instance_key }}"
        group: qconsp

- name: Deploy
  hosts: "qconsp-{{ service_name }}-{{ service_env }}"
  become: yes
  tasks:
    - name: Deploying QConSP Service
      docker_container:
        name: "qconsp-{{ service_name }}"
        image: "lowbit/qconsp-{{ service_name }}:{{ service_version }}"
        ports:
         - "80:{{ service_internal_port }}"
        state: started
        restart_policy: always
