---
- name: Google Cloud Platform
  hosts: localhost
  connection: local
  vars:
    official_image: "official-image-{{ os_image }}"
  tasks:
    - name: Creating Instance
      gce:
        credentials_file: "gcp_key.json"
        disk_auto_delete: yes
        disk_size: 10
        external_ip: ephemeral
        image: "{{ official_image }}"
        machine_type: n1-standard-1
        name: "qconsp-{{ service_name }}-{{ service_env }}"
        network: default
        num_instances: 1
        project_id: united-strategy-231002
        service_account_email: shippable@united-strategy-231002.iam.gserviceaccount.com
        state: present
        tags:
          - http-server
          - "{{ service_env }}"
        zone: us-central1-a
        metadata: '{"enable-oslogin":"TRUE"}'
      register: gce_instance_info
    
    - name: Destroying Instance (if wrong image is being used)
      gce:
        credentials_file: "gcp_key.json"
        disk_auto_delete: yes
        external_ip: ephemeral
        machine_type: n1-standard-1
        name: "qconsp-{{ service_name }}-{{ service_env }}"
        network: default
        num_instances: 1
        project_id: united-strategy-231002
        service_account_email: shippable@united-strategy-231002.iam.gserviceaccount.com
        state: absent
        tags:
          - http-server
          - "{{ service_env }}"
        zone: us-central1-a
        metadata: '{"enable-oslogin":"TRUE"}'
      when: gce_instance_info.instance_data.0.image != official_image

    - name: Creating Instance again (just in case of wrong image was being used)
      gce:
        credentials_file: "gcp_key.json"
        disk_auto_delete: yes
        disk_size: 10
        external_ip: ephemeral
        image: "{{ official_image }}"
        machine_type: n1-standard-1
        name: "qconsp-{{ service_name }}-{{ service_env }}"
        network: default
        num_instances: 1
        project_id: united-strategy-231002
        service_account_email: shippable@united-strategy-231002.iam.gserviceaccount.com
        state: present
        tags:
          - http-server
          - "{{ service_env }}"
        zone: us-central1-a
        metadata: '{"enable-oslogin":"TRUE"}'
      register: gce_instance_info

    - name: Waiting for instance to become active (SSH)
      wait_for:
        delay: 1
        host: "{{ gce_instance_info.instance_data.0.public_ip }}"
        port: 22
        state: started
        timeout: 90

    - name: Updating the external_ip of this instance in Shippable Resource
      shell: shipctl post_resource_state_multi "vm_{{ service_name }}_{{ service_env }}_ip" "external_ip={{ gce_instance_info.instance_data.0.public_ip }}"
