- name: Inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Adding Google Cloud instance to the inventory
      add_host:
        name: "meetup-{{ meetup_env }}"
        ansible_host: "{{ meetup_vm_ip }}"
        ansible_user: lowbit_lowbit_com_br
        ansible_ssh_private_key_file: "{{ instance_key }}"
        group: meetup

- name: Configure Hosts
  hosts: "meetup-{{ meetup_env }}"
  become: yes
  tasks:
    - name: Deploy Meetup Application
      docker_container:
        name: meetup-app
        image: "lowbit/meetup-app:{{ meetup_version }}"
        state: started
        ports:
         - "80:3000"
